server:
  port: ${PORT:8081}

spring:
  application:
    name: routes-service-gateway
  cloud:
    gateway:
      routes:
        - id: routes_command_route
          uri: http://localhost:8045/
          predicates:
            - Path=/api/routes/**
            - Method=POST
          filters:
            - RewritePath= /api/routes/(?<segment>.*),/command/routes/$\{segment}
        - id: routes_query_route
          uri: http://localhost:8046/
          predicates:
            - Method=GET
            - Path=/api/routes/**
          filters:
            - RewritePath= /api/routes/(?<segment>.*),/query/routes/$\{segment}
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - HEAD
              - PUT
              - DELETE
              - PATH