server:
  servlet:
    context-path: /query/routes
  port: ${PORT:8046}

spring:
  application:
    name: routes_service_query
  cloud:
    stream:
      bindings:
        input:
          destination: routings-events
          consumer.headerMode: headers
          contentType: application/json
          group: routes-query-group-1